[package]
name = "spiel"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["dep:zbus"]

[dependencies]
assert_matches = { version = "1.5.0", default-features = false }
bitflags = "2.4.2"
enumflags2 = "0.7.9"
nom = { version = "8.0.0", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
zbus = { version = "4.1.2", optional = true }

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread","net","io-util"] }
spiel = { path = ".", features = ["client"] }
